tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "fish"
brew "git"
brew "gpg"
brew "mas"
brew "neovim"
brew "pinentry-mac"
cask "1password-cli"
cask "alacritty"
cask "dash"
cask "notion"
cask "soulver"
mas "DaisyDisk", id: 411643860
