brew_path=`brew --prefix`

. ${HOME}/.bash/colors
. ${HOME}/.bash/aliases
. ${HOME}/.bash/completions
. ${HOME}/.bash/paths
. ${HOME}/.bash/config

# use .localrc for settings specific to one system
[[ -f ${HOME}/.localrc ]] && . ${HOME}/.localrc
